//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studyzy.IMEWLConverter.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource4Test {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource4Test() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studyzy.IMEWLConverter.Test.Resource4Test", typeof(Resource4Test).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爱存不存	1	ai cun bu cun
        ///控制台应用程序	1	kong zhi tai ying yong cheng xu
        ///原封不动	1	yuan feng bu dong
        ///做做词库	1	zuo zuo ci ku
        ///深蓝居	1	shen lan ju
        ///做做培训	1	zuo zuo pei xun
        ///做做事情	1	zuo zuo shi qing
        ///电子科技大学	1	dian zi ke ji da xue
        ///做做数据库	1	zuo zuo shu ju ku
        ///栋力无限	1	dong li wu xian.
        /// </summary>
        internal static string GooglePinyin {
            get {
                return ResourceManager.GetString("GooglePinyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爱存不存
        ///控制台应用程序
        ///原封不动
        ///做做词库
        ///深蓝居
        ///做做培训
        ///做做事情
        ///电子科技大学
        ///做做数据库
        ///栋力无限
        ///.
        /// </summary>
        internal static string NoPinyinWordOnly {
            get {
                return ResourceManager.GetString("NoPinyinWordOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人民很行xing
        ///人民银行hang
        ///栋力无wu限
        ///深shen蓝lan居ju
        ///爱存不存
        ///电子科技大da学
        ///控制台应用程序
        ///原封不动
        ///做做数shu据库
        ///做做词库
        ///.
        /// </summary>
        internal static string PinyinJiajia {
            get {
                return ResourceManager.GetString("PinyinJiajia", resourceCulture);
            }
        }
    }
}
