//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studyzy.IMEWLConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dictionaries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionaries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studyzy.IMEWLConverter.Dictionaries", typeof(Dictionaries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日	a
        ///曰	a
        ///昌	aa
        ///昍	aa
        ///晶	aaa
        ///晿	aaa
        ///曑	aaah
        ///曡	aaam
        ///曐	aaam
        ///曟	aaav
        ///覸	aabuu
        ///焸	aaf
        ///鷼	aahaf
        ///暒	aahm
        ///暥	aajv
        ///暘	aamh
        ///晘	aamj
        ///晹	aaph
        ///暍	aapv
        ///曝	aate
        ///暻	aayf
        ///明	ab
        ///冐	ab
        ///暝	abac
        ///曖	abbe
        ///暧	abbe
        ///盟	abbt
        ///覵	abbuu
        ///焽	abf
        ///晭	abgr	ab&apos;gr
        ///鷳	abhaf
        ///猒	abik
        ///曌	abjcm
        ///暈	abjj
        ///暉	abjj
        ///晕	abkq
        ///晖	abkq
        ///暖	abme
        ///琞	abmgi
        ///晍	abmr	ab&apos;mr
        ///勗	abms
        ///暩	abof
        ///暚	abou
        ///昷	abt
        ///冒	abu
        ///晛	abuu
        ///昖	aci
        ///暡	acim
        ///顕	acmbc
        ///晜	acnh
        ///昐	acsh
        ///杲	ad
        ///晽	add
        ///鷴	adhaf
        ///晰	adhl
        ///时	adi
        ///昩	adj
        ///暐	admq
        ///暕	adwf	adw&apos;f
        ///鄤	aenl
        ///炅	af
        ///炚	af
        ///曭	afbf
        ///暽	afdq
        ///晱	af [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cangjie5 {
            get {
                return ResourceManager.GetString("Cangjie5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8140	丂	gnv		kao3,yu2
        ///8141	丄	hgd		shang4
        ///8142	丅	ghk		xia4
        ///8143	丆	dgt		shi2
        ///8144	丏	ghnn		mian3
        ///8145	丒	vygf		
        ///8146	丗	gkgd		shi4
        ///8147	丟	gcu		diu1
        ///8148	丠	uxgf		qiu1
        ///8149	両	gmmk		liang3
        ///814A	丣	gajn	gjan	you3
        ///814B	並	uogf	uof	bing4
        ///814C	丩	nhk		jiu1
        ///814D	丮	nfhk	ngk	ji3
        ///814E	丯	ehk		jie4
        ///814F	丱	njhg	jnhg	guan4
        ///8150	丳	kkjk		chan3
        ///8151	丵	oguf	oufj	zhuo2
        ///8152	丷	uyt		ba1
        ///8153	丼	fjyi		jing3
        ///8154	乀	yyll		fu2
        ///8155	乁	yyll	gyi	yi2
        ///8156	乂	qty	rty	yi4
        ///8157	乄	nyi		
        ///8158	乆	nwi		jiu3
        ///8159	乊	tur	tue	hu1
        ///815 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChineseCode {
            get {
                return ResourceManager.GetString("ChineseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ├	ia
        ///┤	ia
        ///⺄	ib
        ///⺈	it
        ///⺋	i/
        ///⺋	ifjl
        ///⺌	if
        ///⺗	ifo
        ///⺗	id
        ///⺗	ido
        ///⺧	iqa
        ///⺪	im
        ///⺪	imjz
        ///⺮	iqiz
        ///⺳	ipt
        ///⺳	ip
        ///⺶	iihz
        ///⺷	ii
        ///⺷	iiha
        ///⺻	in
        ///⻊	il
        ///㑇	iftn
        ///㑳	iftm
        ///㖞	illg
        ///㘚	ilnj
        ///㤘	iotn
        ///㧏	iugr
        ///㧐	iu..
        ///㩳	iufy
        ///㭎	ixgr
        ///㱮	ikgj
        ///㳠	icko
        ///䁖	igij
        ///䅟	iq.k
        ///䌷	i/gj
        ///䎱	ihgs
        ///䓖	ibo,
        ///䙡	ipgj
        ///䜣	ipej
        ///䜩	ipja
        ///䝼	igha
        ///䥇	izpk
        ///䥺	iz;d
        ///䦃	izbj
        ///䦅	izih
        ///䦆	izgh
        ///䦟	inff
        ///䦶	iutn
        ///䦷	iuff
        ///䲟	itt;
        ///䲠	ithk
        ///䲡	itij
        ///䲢	idtg
        ///䲢	idih
        ///䲣	iaqr
        ///䴓	ijtp
        ///䴔	iytp
        ///䴕	iktp
        ///䴖	ihtp
        ///䴗	igtp
        ///䴘	ietp
        ///䴙	intp
        ///䶮	ikhr
        ///一	iz
        ///一	y
        ///一	yz
        ///丁	dj&apos;
        ///丁	dje
        ///丁	dju [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Erbi {
            get {
                return ResourceManager.GetString("Erbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,a
        ///2,ai
        ///3,an
        ///4,ang
        ///5,ao
        ///7,ba
        ///8,bai
        ///9,ban
        ///10,bang
        ///11,bao
        ///12,bei
        ///13,ben
        ///14,beng
        ///15,bi
        ///16,bian
        ///18,biao
        ///19,bie
        ///20,bin
        ///21,bing
        ///22,bo
        ///23,bu
        ///25,ca
        ///26,cai
        ///27,can
        ///28,cang
        ///29,cao
        ///30,ce
        ///31,cen
        ///32,ceng
        ///33,cha
        ///34,chai
        ///35,chan
        ///36,chang
        ///37,chao
        ///38,che
        ///39,chen
        ///40,cheng
        ///41,chi
        ///42,chong
        ///43,chou
        ///44,chu
        ///45,chuai
        ///46,chuan
        ///47,chuang
        ///48,chui
        ///49,chun
        ///50,chuo
        ///51,ci
        ///52,cong
        ///53,cou
        ///54,cu
        ///56,cuan
        ///59,cui
        ///60,cun
        ///61,cuo
        ///63,da
        ///64,dai
        ///65,dan
        ///66,dang
        ///67,dao
        ///68,de
        ///69,dei
        ///70,den
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TouchPalPinyinDic {
            get {
                return ResourceManager.GetString("TouchPalPinyinDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;zeng&apos;yi 曾毅
        ///&apos;yin&apos;yue 音乐
        ///&apos;jin&apos;xing 进行
        ///&apos;liao&apos;jie 了解
        ///&apos;diao&apos;cha 调查
        ///&apos;mu&apos;di 目的
        ///&apos;ji&apos;ou 奇偶
        ///&apos;he&apos;le 饸饹
        ///&apos;xing&apos;wei 行为
        ///&apos;zhi&apos;xing 执行
        ///&apos;chong&apos;qing 重庆
        ///&apos;shi&apos;xing 实行
        ///&apos;ju&apos;xing 举行
        ///&apos;diao&apos;yan 调研
        ///&apos;gan&apos;jue 感觉
        ///&apos;chang&apos;qi 长期
        ///&apos;yun&apos;xing 运行
        ///&apos;liu&apos;xing 流行
        ///&apos;jue&apos;de 觉得
        ///&apos;zhu&apos;ming 著名
        ///&apos;qiang&apos;diao 强调
        ///&apos;xing&apos;dong 行动
        ///&apos;chong&apos;xin 重新
        ///&apos;xian&apos;zhu 显著
        ///&apos;fa&apos;xing 发行
        ///&apos;chang&apos;de 长的
        ///&apos;bu&apos;liao 不了
        ///&apos;zi&apos;jue 自觉
        ///&apos;zi&apos;xing 自行
        ///&apos;xi&apos;zang 西藏
        ///&apos;chang&apos;chun 长春
        ///&apos;zi&apos;xi 仔细
        ///&apos;chang&apos;sha 长沙
        ///&apos;lv&apos;xing 履行
        ///&apos;jue&apos;se 角色
        ///&apos;pian&apos;yi 便宜
        ///&apos;chang&apos;jiang 长江
        ///&apos;chong&apos;fu  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordPinyin {
            get {
                return ResourceManager.GetString("WordPinyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 丨	ia	iaaa				
        ///丩	zi	ziaa				
        ///丬	ti	tia 				
        ///丫	ui	udi 				
        ///丰	ci	ci 				
        ///中	jv	j 	jivv			
        ///丮	yb	ydab				
        ///丯	ci	pdi 				
        ///丱	zi	ziaa				
        ///卡	ia	iai 	idai	iid 		
        ///串	jj	jji 	jjv 			
        ///丳	jj	jjnd				
        ///卥	ij	idos				
        ///临	km	kdmk	kmk 			
        ///亅	ia	iaaa				
        ///亊	du	duxb				
        ///事	dj	ajx 	dj 	djx 	djxb	
        ///乀	yd	ydaa				
        ///乁	yd	ydaa				
        ///丿	ma	maaa				
        ///乃	ym	ymv 	ymvv			
        ///乂	os	osa 				
        ///乄	zs	msvv	osaa	zsvv		
        ///九	qy	qy 				
        ///亇	ri	mxi 	rivv			
        ///久	rs	rsv 	rsvv			
        ///么	mz	mzs 				
        ///乇	mh	mhd 				
        ///乊	mu	mud 				
        ///乆	zo	zod 				
        ///丸	qs	qya 	qys 	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Zhengma {
            get {
                return ResourceManager.GetString("Zhengma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ㄚ	a
        ///ㄞ	ai
        ///ㄢ	an
        ///ㄤ	ang
        ///ㄠ	ao
        ///ㄅㄚ	ba
        ///ㄅㄞ	bai
        ///ㄅㄢ	ban
        ///ㄅㄤ	bang
        ///ㄅㄠ	bao
        ///ㄅㄟ	bei
        ///ㄅㄣ	ben
        ///ㄅㄥ	beng
        ///ㄅㄧ	bi
        ///ㄅㄧㄢ	bian
        ///ㄅㄧㄠ	biao
        ///ㄅㄧㄝ	bie
        ///ㄅㄧㄣ	bin
        ///ㄅㄧㄥ	bing
        ///ㄅㄛ	bo
        ///ㄅㄨ	bu
        ///ㄘㄚ	ca
        ///ㄘㄞ	cai
        ///ㄘㄢ	can
        ///ㄘㄤ	cang
        ///ㄘㄠ	cao
        ///ㄘㄜ	ce
        ///ㄘㄣ	cen
        ///ㄘㄥ	ceng
        ///ㄔㄚ	cha
        ///ㄔㄞ	chai
        ///ㄔㄢ	chan
        ///ㄔㄤ	chang
        ///ㄔㄠ	chao
        ///ㄔㄜ	che
        ///ㄔㄣ	chen
        ///ㄔㄥ	cheng
        ///ㄔㄨㄥ	chong
        ///ㄔㄡ	chou
        ///ㄔㄨ	chu
        ///ㄔㄨㄞ	chuai
        ///ㄔㄨㄢ	chuan
        ///ㄔㄨㄤ	chuang
        ///ㄔㄨㄟ	chui
        ///ㄔㄨㄣ	chun
        ///ㄔㄨㄛ	chuo
        ///ㄘㄨㄥ	cong
        ///ㄘㄡ	cou
        ///ㄘㄨ	cu
        ///ㄘㄨㄢ	cuan
        ///ㄘㄨㄟ	cui
        ///ㄘㄨㄣ	cun
        ///ㄘㄨㄛ	cuo
        ///ㄉㄚ	da
        ///ㄉㄞ	dai
        ///ㄉㄢ	dan
        ///ㄉㄤ	dang
        ///ㄉㄠ	dao
        ///ㄉㄜ	de
        ///ㄉㄟ	dei
        ///ㄉㄥ	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Zhuyin {
            get {
                return ResourceManager.GetString("Zhuyin", resourceCulture);
            }
        }
    }
}
