<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>ImeWlConverter.Core</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImeWlConverter.Abstractions\ImeWlConverter.Abstractions.csproj"/>
        <ProjectReference Include="..\ImeWlConverter.CodeData\ImeWlConverter.CodeData.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7"/>
        <PackageReference Include="SharpZipLib" Version="1.4.2"/>
        <PackageReference Include="UTF.Unknown" Version="2.5.1"/>
    </ItemGroup>

</Project>
